ptxd_make_cmake_toolchain: fix CMAKE_SYSTEM_PROCESSOR for x86
CMAKE_SYSTEM_PROCESSOR defaults to 'uname -m' and this is i*86 for
32-bit x86. So just use $PTXCONF_ARCH_STRING.

Without this building qt6 fails with:

In file included from .../qtmultimedia/src/3rdparty/pffft/pffft.c:141:
.../include/xmmintrin.h: In function 'passf2_ps':
.../include/xmmintrin.h:193:1: error: inlining failed in call to 'always_inline' '_mm_sub_ps': target specific option mismatch
.../qtmultimedia/src/3rdparty/pffft/pffft.c:148:19: note: called from here
.../qtmultimedia/src/3rdparty/pffft/pffft.c:290:23: note: in expansion of macro 'VSUB'
[...]

Because -DPFFFT_SIMD_DISABLE is not added to COMPILE_OPTIONS.

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>