qt5: fix missing limits includes in qtdeclarative with GCC 11
Fixes these build errors:

  In file included from qt-everywhere-src-5.15.2/qtdeclarative/src/qmldebug/qqmlprofilereventreceiver_p.h:43,
                   from moc_qqmlprofilereventreceiver_p.cpp:10:
  qt-everywhere-src-5.15.2/qtdeclarative/src/qmldebug/qqmlprofilerevent_p.h: In member function 'void QQmlProfilerEvent::assignNumbers(const Container&)':
  qt-everywhere-src-5.15.2/qtdeclarative/src/qmldebug/qqmlprofilerevent_p.h:314:65: error: 'numeric_limits' is not a member of 'std'
  qt-everywhere-src-5.15.2/qtdeclarative/src/qmldebug/qqmlprofilerevent_p.h:314:87: error: expected primary-expression before '>' token
  qt-everywhere-src-5.15.2/qtdeclarative/src/qmldebug/qqmlprofilerevent_p.h:314:90: error: '::max' has not been declared; did you mean 'std::max'?

Signed-off-by: Bastian Krause <bst@pengutronix.de>
Message-Id: <20211201134037.1086230-1-bst@pengutronix.de>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>