strongswan: version bump 5.9.6 -> 5.9.8
Configure options:

* Disabled pki (--disable-pki)
* Removed install tree /usr/bin since it was only used by pki
* scepclient deprecated and removed
* Disabled AddressSanitizer (--disable-asan)
* New --with-python-sys-prefix unspecified for GNU default values
* New --with-python_prefix unspecified for GNU default values
* New --with-python_exec_prefix unspecified for GNU default values
* Disabled extended compiler warnings (--disable-warnings) because of
  compile error: (OSELAS.Toolchain-2021.07.0)

  cmac.c: In function 'derive_key':
  cmac.c:236:36: error: writing 1 byte into a region of size 0
  [-Werror=stringop-overflow=]
  236 |                 rb.ptr[rb.len - 1] = 0x87;
      |                 ~~~~~~~~~~~~~~~~~~~^~~~~~
  cc1: all warnings being treated as errors

Plugins:

* Fixed missing plugin targetinstall of libstrongswan-acert.so
* Enabled mgf1 since swanctl and starting strongswan gave following
  error:

plugin 'mgf1': failed to load - mgf1_plugin_create not found and no
plugin file available

Signed-off-by: Lars Pedersen <lapeddk@gmail.com>
Message-Id: <20221215091123.31935-1-lapeddk@gmail.com>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>