boost: build with boost.stacktrace.from_exception=off for x86 (32-bit)
It's not supported here:

libs/stacktrace/build/../src/from_exception.cpp:170:2: error: #error On
this platform memory leaks are possible if capturing stacktrace from
exceptions is enabled and exceptions are thrown concurrently and libc++
runtime is used. Define
`BOOST_STACKTRACE_LIBCXX_RUNTIME_MAY_CAUSE_MEMORY_LEAK` to suppress this
error if the library would not be used with libc++ runtime (for example,
it would be only used with GCC runtime). Otherwise, disable the
boost_stacktrace_from_exception library build (for example by `./b2
boost.stacktrace.from_exception=off` option).

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>