host-python3-flit-core: select HOST_PYTHON3_ZLIB
When host-python3 was built before host-zlib, there is no zlib support.

Fixes the following error when building the wheel from
build-host/flit_core-3.8.0:

  RuntimeError: Compression requires the (missing) zlib module

Caused by this function invocation:

  zipfile.ZipFile(target_fp, 'w', compression=zipfile.ZIP_DEFLATED)

Signed-off-by: Markus Heidelberg <m.heidelberg@cab.de>
Message-Id: <20250507113809.2818183-1-m.heidelberg@cab.de>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>