libpng: version bump 1.6.37 -> 1.6.38
Effectively reverts parts of
249544ffd ("libpng: version bump 1.6.29 -> 1.6.34").

"--enable-arm-neon=check" leads to problems on ARM64, such as:

  arm/arm_init.c:39:6: error: #error "PNG_ARM_NEON_CHECK_SUPPORTED must not be defined on this platform"

The check mechanism is not recommended anyway [1]:

  WARNING: it is strongly recommended that you do not build libpng with
  run-time checks for CPU features if at all possible.  In the case of the ARM
  NEON instructions there is no processor-specific way of detecting the
  presence of the required support, therefore run-time detection is extremely
  OS specific.

So stick to yes/no for the ARM NEON option by switching to the ptx/yesno
macro.

[1] https://sourceforge.net/p/libpng/code/ci/v1.6.38/tree/arm/arm_init.c#l21

Signed-off-by: Bastian Krause <bst@pengutronix.de>
Message-Id: <20221005102705.2346939-1-bst@pengutronix.de>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>