alsa-lib: add missing use-case-manager -> mixer dependency
Fixes the following build failure if ALSA_LIB_UCM is enabled but
ALSA_LIB_MIXER is disabled:

    CCLD     libasound.la
  .../arm-v7a-linux-gnueabihf/bin/ld: ucm/.libs/libucm.a(main.o): in function `snd_use_case_parse_selem_id':
  .../alsa-lib-1.2.1.2/src/ucm/main.c:1968: undefined reference to `snd_mixer_selem_id_parse'

Signed-off-by: Philipp Zabel <p.zabel@pengutronix.de>
Acked-by: Juergen Borleis <jbe@pengutronix.de>
Message-Id: <20200225170302.1037-1-p.zabel@pengutronix.de>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>