host-ckermit: build wit -std=gnu11
gcc 15 defaults to gnu23 and that causes the build to fail with:

ckuusr.c:8275:15: error: too many arguments to function 'dosexp'; expected 0, have 1

ckuus3.c:4025:17: error: expected identifier or '(' before 'true'
ckuus3.c:4042:22: error: lvalue required as left operand of assignment

Use an older standard to avoid this.

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>