host-libcap-ng: fix building with old glibc versions
Without this build with older glibc (at least 2.27 and older) versions
fails with:

.../libcap-ng-0.7.10/src/.libs/libcap-ng.so: undefined reference to `pthread_atfork'

Newer glibc versions have some magic to handle this internally.

Just link to libpthread to avoid this. It's just a host library so it
doesn't matter if this is done needlessly.

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>