host-system-python3-setuptools: select host-system-python3-packaging
It's not strictly needed because it has a vendored copy. Unfortunately,
if a too old version is installed in the system, that will be used
anyways and building fails with:

ImportError: Cannot import `packaging.licenses`.
        Setuptools>=77.0.0 requires "packaging>=24.2" to work properly.
        Please make sure you have a suitable version installed.

So make sure our own version is built first.

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>