host-unifdef: build wit -std=gnu11
gcc 15 defaults to gnu23 and that causes the build to fail with:

unifdef.c:205:1: warning: useless type name in empty declaration
unifdef.c:205:1: error: 'constexpr' in empty declaration
unifdef.c: In function 'eval_unary':
unifdef.c:1089:27: error: expected identifier or '(' before '=' token
unifdef.c:1106:27: error: expected identifier or '(' before '=' token
unifdef.c: In function 'ifeval':
unifdef.c:1173:19: error: expected identifier or '(' before '=' token
unifdef.c:1176:27: error: expected specifier-qualifier-list before '?' token

Use an older standard to avoid this.

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>