host-yasm: build wit -std=gnu11
gcc 15 defaults to gnu23 and that causes the build to fail with:

./libyasm/bitvect.h:88:32: error: cannot use keyword 'false' as enumeration constant
./libyasm/bitvect.h:88:32: note: 'false' is a keyword with '-std=c23' onwards

Use an older standard to avoid this.

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>