python3-pyyaml: install missing cyaml library
_yaml.cpython-*.so was accidentally omitted before. Now make sure to
install this library to make the libyaml bindings work.

Before:
  >>> from yaml.cyaml import *
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/lib/python3.7/site-packages/yaml/cyaml.py", line 5, in <module>
  ModuleNotFoundError: No module named '_yaml'

Now:
  >>> from yaml.cyaml import *
  >>>

Signed-off-by: Bastian Krause <bst@pengutronix.de>
Message-Id: <20211201162730.2510267-1-bst@pengutronix.de>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>