host-glslang: add missing dependency
Otherwise, building may fails with:

In file included from .../build-host/glslang-1.3.280.0/SPIRV/GlslangToSpv.cpp:46:
.../build-host/glslang-1.3.280.0/SPIRV/SpvTools.h:47:10: fatal error: spirv-tools/libspirv.h: No such file or directory

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>