iputils: Fix targetinstall
The tools are all optional.  If no tool to be installed in /usr/bin is
selected, targetinstall fails.  Same for tools going to /usr/sbin. See
for example following log of failed targetinstall, if only arping and
ping are selected, but none of the others:

    install file:
      src=rsu/platform-v7a/packages/iputils-s20200821/usr/bin/arping
      dst=/usr/bin/arping
      owner=0
      group=0
      permissions=0755
      debug file: /usr/lib/debug/.build-id/51/e139e0e79232c85ddadeb45ae7ecc901d4073c.debug

    install file:
      src=rsu/platform-v7a/packages/iputils-s20200821/usr/bin/ping
      dst=/usr/bin/ping
      owner=0
      group=0
      permissions=0755
      debug file: /usr/lib/debug/.build-id/93/03312f626e591bc167b0e7e2a9b38c71d4bc7b.debug

    No suitable file '/usr/sbin' could be found in any of these locations:
    /home/adahl/[…]/rsu/platform-v7a/packages/iputils-s20200821/usr/sbin.v7a
    /home/adahl/[…]/rsu/platform-v7a/packages/iputils-s20200821/usr/sbin

    Error: install_tree failed!

Fixes: 928752d3a0bc ("iputils: version bump s20180629 -> s20200821")
Signed-off-by: Alexander Dahl <ada@thorsis.com>
Message-Id: <20210525163015.59080-1-ada@thorsis.com>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>