python3: ensurepip requires hashlib/SSL
Otherwise ensurepip fails with the following error:

  Traceback (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    File "/usr/lib/python3.7/__init__.py", line 5, in <module>
    File "/usr/lib/python3.7/tempfile.py", line 45, in <module>
    File "/usr/lib/python3.7/random.py", line 46, in <module>
  ModuleNotFoundError: No module named 'hashlib'

Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>
Message-Id: <20200716080840.2963-1-r.czerwinski@pengutronix.de>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>