binutils: disable gprofng to fix build with host java installed
Explicitly disable gprofng to avoid a build failure:

  make[5]: Entering directory '.../build-target/binutils-2.39/gprofng/libcollector'
    CC       libgp_collector_la-jprofile.lo
  jprofile.c:32:10: fatal error: jni.h: No such file or directory

if the binutils build system manages to find a Java host installation.
Use an environment variable instead of the --disable-gprofng configure
option for compatibility with older binutils versions.

Signed-off-by: Philipp Zabel <p.zabel@pengutronix.de>
Message-Id: <20221202125811.2834144-1-p.zabel@pengutronix.de>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>