ptxd_install_error: don't unlock
In some cases ptxd_install_error() is called without holding a lock. The
result is a bogus error message. And the shell exits immediately anyways.
At that point all open file descriptors a closed and all locks are
released.

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>