networkmanager: Version bump 1.30.4 to 1.44.2
dnssec_trigger and iptables configure options has been removed

select PPP_MS_CHAP if NETWORKMANAGER_PPP is enabled to fix compile error:
  ../NetworkManager-1.44.2/src/core/ppp/nm-pppd-compat.c:50:10: fatal
  error: pppd/chap_ms.h: No such file or directory
     50 | #include <pppd/chap_ms.h>

Flag NETWORKMANAGER_POLKIT as BROKEN because of following error:

FAILED: data/org.freedesktop.NetworkManager.policy
.../sysroot-host/usr/bin/meson --internal msgfmthelper
--msgfmt=.../sysroot-host/usr/bin/msgfmt
data/org.freedesktop.NetworkManager.policy.in
data/org.freedesktop.NetworkManager.policy xml
.../build-target/NetworkManager-1.44.2/po
.../sysroot-host/usr/bin/msgfmt: cannot locate ITS rules for
data/org.freedesktop.NetworkManager.policy.in

Signed-off-by: Lars Pedersen <lapeddk@gmail.com>
Message-Id: <20231201141552.184101-1-lapeddk@gmail.com>
[mol: remove obsolete patch]
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>