host-jimtcl: build with --shared
Otherwise users of the library (e.g. host-openocd) need to know the
implicit dependencies. libjim now (at least since 0.80) uses libutil for
openpty().

Without this host-openocd fails to build with:

/usr/bin/ld: .../sysroot-host/lib/libjim.a(jim-aio.o): in function `JimAioOpenPtyCommand':
.../build-host/jimtcl-0.80/jim-aio.c:2070: undefined reference to `openpty'
collect2: error: ld returned 1 exit status

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>