logrotate: version bump 3.9.1 -> 3.17.0
Build of the old version fails with recent OSELAS toolchain 2020.08.x,
error log in the end.  Runtime tested on at91 based target.

Noteworthy changes from upstream ChangeLog affecting this package
(collected from multiple versions):

  - Upstream moved to GitHub: <https://github.com/logrotate/logrotate>.
  - Legacy Makefile renamed to Makefile.legacy, will be removed eventually.
  - Allow to change default state path at build time (via the
    --with-state-file-path option of the configure script).
  - Import systemd service and timer for logrotate from openSUSE.
  - Avoid using local implementation of strndup() and asprintf() if these
    functions are available at build time.
  - Fix parsing of 'su' directive to accept usernames starting with numeric
    symbols.
  - Make sure that 64-bit file offsets are used on 32-bit systems.
  - Errors in config files are no longer treated as fatal errors. (#81)
  - `configure --with-default-mail-command` specifies default mail command. (#100)
  - build fixes related to `-Werror` (#119) and `-Werror=format=` (#108)
  - `confgure --enable-werror` now controls use of the -Werror flag (#123)
  - fix compilation with gcc-10, which defaults to `-fno-common` (#288)
  - lock state file to prevent parallel execution of logrotate (#295, #297)

And of course lots of other bugfixes and improvements.

The download URL was changed to the official upstream source on GitHub,
while at it, switched to .xz compressed tarballs.

The license hash changed, because upstream replaced the document with a
recent version from GNU for 3.12.0.

The license identifier was clearified by upstream to GPLv2+ in
logrotate.spec.in for 3.11.0.

The whole patch series can be dropped for the following reasons:

- '0001-deb-config-h.patch': Debian patch introduced with 878707bd943a
  ("logrotate: version bump to 3.9.1"), those options are set through
  ./configure in prepare stage now for backwards compatibility
- '0002-datehack.patch': upstream included this as bdbfea38a154
  ("Support system dates back to the year 1970") for 3.9.2
- '0003-cpp-crossbuild.patch': related to legacy makefile based build
- '0004-chown-484762.patch': Debian patch, they dropped it in recent
  versions
- '0005-configure-add-check-for-large-file-support.patch': similar patch
  ceb2653c08b5 ("configure.ac: make sure that 64-bit file offsets are
  used") added by upstream for 3.11.0

Build error log with gcc-10:

  -------------------------
  target: logrotate.compile
  -------------------------

  make: Entering directory '/home/adahl/Work/bsp/tt/ncl/platform-ncl/build-target/logrotate-3.9.1'
  Making all in test
  make[1]: Entering directory '/home/adahl/Work/bsp/tt/ncl/platform-ncl/build-target/logrotate-3.9.1/test'
  make[1]: Nothing to be done for 'all'.
  make[1]: Leaving directory '/home/adahl/Work/bsp/tt/ncl/platform-ncl/build-target/logrotate-3.9.1/test'
  make[1]: Entering directory '/home/adahl/Work/bsp/tt/ncl/platform-ncl/build-target/logrotate-3.9.1'
    CC       logrotate.o
    CC       config.o
    CC       log.o
    CC       basenames.o
  config.c: In function 'strndup':
  config.c:87:10: warning: 'nonnull' argument 's' compared to NULL [-Wnonnull-compare]
  logrotate.c: In function 'postrotateSingleLog':
  logrotate.c:1786:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
  logrotate.c:1789:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
  logrotate.c: In function 'prerotateSingleLog':
  logrotate.c:1225:2: warning: 'strncat' specified bound depends on the length of the source argument [-Wstringop-overflow=]
  logrotate.c:1226:3: note: length computed here
    CCLD     logrotate
  /opt/OSELAS.Toolchain-2020.08.0/arm-v5te-linux-gnueabi/gcc-10.2.1-glibc-2.32-binutils-2.35-kernel-5.8-sanitized/lib/gcc/arm-v5te-linux-gnueabi/10.2.1/../../../../arm-v5te-linux-gnueabi/bin/ld: config.o:platform-ncl/build-target/logrotate-3.9.1/logrotate.h:77: multiple definition of `logs'; logrotate.o:platform-ncl/build-target/logrotate-3.9.1/logrotate.h:77: first defined here
  collect2: error: ld returned 1 exit status
  make[1]: *** [Makefile:402: logrotate] Error 1
  make[1]: Leaving directory '/home/adahl/Work/bsp/tt/ncl/platform-ncl/build-target/logrotate-3.9.1'
  make: *** [Makefile:442: all-recursive] Error 1
  make: Leaving directory '/home/adahl/Work/bsp/tt/ncl/platform-ncl/build-target/logrotate-3.9.1'
  make: *** [/usr/local/lib/ptxdist-2020.10.0/rules/post/ptxd_make_world_compile.make:20: /home/adahl/Work/bsp/tt/ncl/platform-ncl/state/logrotate.compile] Error 2

Cc: Marc Kleine-Budde <mkl@pengutronix.de>
Signed-off-by: Alexander Dahl <ada@thorsis.com>
Message-Id: <20201022084340.20510-3-ada@thorsis.com>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>