python3-pysnmp: new package
Got a runtime error so py files are installed instead of pyc

Traceback (most recent call last):
  File "/usr/bin/snmptrap.py", line 237, in <module>
  snmpEngine = engine.SnmpEngine()
  File "/usr/lib/python3.7/site-packages/pysnmp/entity/engine.py", line 63, in __init__
  File "/usr/lib/python3.7/site-packages/pysnmp/proto/rfc3412.py", line 32, in __init__
  File "/usr/lib/python3.7/site-packages/pysnmp/smi/builder.py", line 401, in loadModules
  File "/usr/lib/python3.7/site-packages/pysnmp/smi/builder.py", line 341, in loadModule
  File "/usr/lib/python3.7/site-packages/pysnmp/smi/builder.py", line 143, in read
  ValueError: bad marshal data (unknown type code)

Signed-off-by: Lars Pedersen <lapeddk@gmail.com>
Message-Id: <20210719074703.25316-1-lapeddk@gmail.com>
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>