SBoM: CycloneDX: fix missing defusedxml dependency
Enabling CycloneDX report generation on a clean host environment result
in missing defusedxml python3 module.

------------------------------
target: image-root-tgz.reports
------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/ptxdist-2025.06.0/scripts/generate-report.py", line 72, in <module>
    main()
    ~~~~^^
  File "/usr/local/lib/ptxdist-2025.06.0/scripts/generate-report.py", line 59, in main
    from report.cyclonedx_sbom import CycloneDXSbomGenerator
  File "/usr/local/lib/ptxdist-2025.06.0/scripts/report/cyclonedx_sbom.py", line 11, in <module>
    from cyclonedx.factory.license import LicenseFactory
  File "/builds/emperor/ptxdist/platform-emperor/sysroot-host/usr/lib/system-python3/lib64/python3.13/site-packages/cyclonedx/factory/license.py", line 21, in <module>
    from ..model.license import DisjunctiveLicense, LicenseExpression
  File "/builds/emperor/ptxdist/platform-emperor/sysroot-host/usr/lib/system-python3/lib64/python3.13/site-packages/cyclonedx/model/__init__.py", line 36, in <module>
    import serializable
  File "/builds/emperor/ptxdist/platform-emperor/sysroot-host/usr/lib/system-python3/lib64/python3.13/site-packages/serializable/__init__.py", line 47, in <module>
    from defusedxml import ElementTree as SafeElementTree  # type:ignore[import-untyped]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'defusedxml'
make: *** [/usr/local/lib/ptxdist-2025.06.0/rules/post/ptxd_make_world_report.make:18: /builds/emperor/ptxdist/platform-emperor/state/image-root-tgz.reports] Error 1

Signed-off-by: Bruno Thomsen <bruno.thomsen@gmail.com>
Message-Id: <20250618192335.17780-1-bruno.thomsen@gmail.com>
[mol: adapt to renamed package]
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>